<a href="https://colab.research.google.com/github/SouravUpadhyay7/NumPY/blob/main/Data_cleaning_and_analysis_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
# None to np.nan

arr = np.array([1,2,3,None, 4,5,None])
print(arr)

arr[arr == None] = np.nan
print(arr)

[1 2 3 None 4 5 None]
[1 2 3 nan 4 5 nan]


In [3]:
# Checking with Null Values


arr = np.array([1,2,3,np.nan, 4,5,np.nan])
print(arr)

print(np.isnan(arr))

[ 1.  2.  3. nan  4.  5. nan]
[False False False  True False False  True]


In [4]:
# Removing null values

arr = np.array([1,2,3,np.nan, 4,5,np.nan])

print(np.isnan(arr))
print(~np.isnan(arr))

arr = arr[~np.isnan(arr)]
print(arr)

[False False False  True False False  True]
[ True  True  True False  True  True False]
[1. 2. 3. 4. 5.]


In [5]:
# Filling null with fixed values


arr = np.array([1,2,3, np.nan, 4,5,np.nan])
print(arr)

arr[np.isnan(arr)] = 0
print(arr)


[ 1.  2.  3. nan  4.  5. nan]
[1. 2. 3. 0. 4. 5. 0.]


In [6]:
# Filling null with average


arr = np.array([21,22,22, np.nan, 24,25,np.nan])
print(arr)

arr[np.isnan(arr)] = int(np.nanmean(arr))
print(arr)

[21. 22. 22. nan 24. 25. nan]
[21. 22. 22. 22. 24. 25. 22.]


In [7]:
arr = np.random.randint(1,11,size=(5,5))
arr

array([[ 3,  7,  8,  2,  5],
       [ 4,  9,  6,  2, 10],
       [ 6,  9, 10,  4,  3],
       [ 2,  8,  7,  7,  5],
       [ 1,  1,  5,  4,  4]])

In [8]:
# Filter elements greater than 5

arr[arr>5]

array([ 7,  8,  9,  6, 10,  6,  9, 10,  8,  7,  7])

In [9]:
# Filter the elements that are even

arr[arr%2 == 0]

array([ 8,  2,  4,  6,  2, 10,  6, 10,  4,  2,  8,  4,  4])

In [10]:
# Filter elements that are both greather than 5 and even

arr[(arr>5) & (arr%2 == 0)]

array([ 8,  6, 10,  6, 10,  8])

In [11]:
# Filter elements that are divisible by either 3 or 7

arr[(arr % 3 == 0) | (arr % 7 == 0)]

array([3, 7, 9, 6, 6, 9, 3, 7, 7])

In [13]:


# Filter elements that based on condition on another array

arr1 = np.array([True, False, True,False,True])

arr[arr1]

array([[ 3,  7,  8,  2,  5],
       [ 6,  9, 10,  4,  3],
       [ 1,  1,  5,  4,  4]])

In [14]:
# Filter the elements based on condition of specific row

filtered_arr = arr[2][arr[2,:] > 5]

filtered_arr

array([ 6,  9, 10])

### Aggregate Functions


In [15]:
# sum


arr = np.array([1,2,3,4,5])
print(np.sum(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.sum(arr))
print(np.sum(arr, axis = 0))
print(np.sum(arr, axis = 1))

15
21
[5 7 9]
[ 6 15]


In [16]:
#  mean

arr = np.array([1,2,3,4,5])
print(np.mean(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.mean(arr))
print(np.mean(arr, axis = 0))
print(np.mean(arr, axis = 1))

3.0
3.5
[2.5 3.5 4.5]
[2. 5.]


In [17]:
#  standard daviation

arr = np.array([1,2,3,4,5])
print(np.std(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.std(arr))
print(np.std(arr, axis = 0))
print(np.std(arr, axis = 1))

1.4142135623730951
1.707825127659933
[1.5 1.5 1.5]
[0.81649658 0.81649658]


In [18]:
# min-max

arr = np.array([1,2,3,4,5])
print(np.min(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.min(arr))
print(np.min(arr, axis = 0))
print(np.min(arr, axis = 1))

print('-'*20)

arr = np.array([1,2,3,4,5])
print(np.max(arr))

arr = np.array([[1,2,3],[4,5,6]])
print(np.max(arr))
print(np.max(arr, axis = 0))
print(np.max(arr, axis = 1))

1
1
[1 2 3]
[1 4]
--------------------
5
6
[4 5 6]
[3 6]


In [19]:

arr = np.random.randint(low = 1, high = 101, size = 100)

mean   = np.mean(arr)
median = np.median(arr)

variance = np.var(arr)
std_dev  = np.std(arr)

q1 = np.percentile(arr, 25)
q2 = np.percentile(arr, 50)
q3 = np.percentile(arr, 75)

iqr = q3 - q1

skewness = np.mean((arr - mean) ** 3) / (std_dev ** 3)
kurtosis = np.mean((arr - mean) ** 4) / (std_dev ** 4)

print('Mean      : ', mean)
print('Median    : ', median)
# print('Mode      : ', mode)
print('-'*20)

print('Variance  : ', variance)
print('Standard  : ', std_dev)
print('-'*20)

print('Q1        : ', q1)
print('Q2        : ', q2)
print('Q3        : ', q3)
print('-'*20)

print('IQR       : ', iqr)
print('Skewness  : ', skewness)
print('Kurtosis  : ', kurtosis)

Mean      :  47.58
Median    :  49.5
--------------------
Variance  :  838.6036
Standard  :  28.958653283604196
--------------------
Q1        :  22.0
Q2        :  49.5
Q3        :  70.25
--------------------
IQR       :  48.25
Skewness  :  0.03865600827394269
Kurtosis  :  1.7777005276537958


In [20]:
# Searching

arr = np.array([1,3,4,6,5,7,12,13])

# Linear Search
index = np.where(arr == 3)[0]
print(index)

# Binary Search
index = np.searchsorted(arr, 3)
print(index)

# Searching Closest Value
index = np.argmin(abs(arr - 11))
print(index)


[1]
1
6


In [21]:
# Sorting

arr = np.array([5,7,9,0,3,1,6,2,4,8])

# Quick Sort
sorted_arr = np.sort(arr)
print(sorted_arr)

# Quick Sort
sorted_arr = np.sort(arr, kind = 'quicksort')
print(sorted_arr)

# Heap Sort
sorted_arr = np.sort(arr, kind = 'heapsort')
print(sorted_arr)

# Merge Sort
sorted_arr = np.sort(arr, kind = 'mergesort')
print(sorted_arr)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [23]:
# Masking with Boolean Arrays

arr7 = np.array([1,2,np.nan,4,5,np.nan])

print(np.isnan(arr7))
print(arr7[np.isnan(arr7)])
print(arr7[~np.isnan(arr7)])

[False False  True False False  True]
[nan nan]
[1. 2. 4. 5.]


In [24]:
# Replacing outliers with s specific value

arr = np.array([1,2,3,4,5,6,7,8,9])

arr[arr > 7] = 7
arr[arr < 3] = 3
print(arr)


[3 3 3 4 5 6 7 7 7]


In [25]:
# Removing the Duplicates


arr = np.array([1,2,2,2,3,3,4,5,6,7,8,9])
print(arr)

unique_arr = np.unique(arr)
print(unique_arr)

print(set(arr))

[1 2 2 2 3 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
{1, 2, 3, 4, 5, 6, 7, 8, 9}


In [26]:
#  Categorical data to One Hot Encoding


categorical_arr = np.array(['A','B','C','D','E'])

numrical_arr = np.array([0,1,2,3,4])

print(categorical_arr)

one_hot_arr = np.eye(5)[numrical_arr]
print(one_hot_arr)

['A' 'B' 'C' 'D' 'E']
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [29]:
#  Data Normalization

arr = np.array([10000,200000,300000,4000000,5000000])

normalized_arr = (arr - arr.min()) / (arr.max() - arr.min())
print(normalized_arr)

[0.         0.03807615 0.05811623 0.7995992  1.        ]
